//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PotatoVN.App.PluginBase.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PotatoVN.App.PluginBase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Create Desktop Shortcut (URI) 的本地化字符串。
        /// </summary>
        internal static string CreateShortcut {
            get {
                return ResourceManager.GetString("CreateShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to Sunshine 的本地化字符串。
        /// </summary>
        internal static string ExportToSunshine {
            get {
                return ResourceManager.GetString("ExportToSunshine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support creating desktop shortcuts (URI) or exporting to Sunshine. 的本地化字符串。
        /// </summary>
        internal static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shortcut &amp; Sunshine 的本地化字符串。
        /// </summary>
        internal static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Desktop shortcut created successfully 的本地化字符串。
        /// </summary>
        internal static string ShortcutCreated {
            get {
                return ResourceManager.GetString("ShortcutCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to create desktop shortcut 的本地化字符串。
        /// </summary>
        internal static string ShortcutCreateFailed {
            get {
                return ResourceManager.GetString("ShortcutCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application already exists in Sunshine. 的本地化字符串。
        /// </summary>
        internal static string SunshineAlreadyExists {
            get {
                return ResourceManager.GetString("SunshineAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exported to Sunshine successfully 的本地化字符串。
        /// </summary>
        internal static string SunshineExported {
            get {
                return ResourceManager.GetString("SunshineExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to export to Sunshine 的本地化字符串。
        /// </summary>
        internal static string SunshineExportFailed {
            get {
                return ResourceManager.GetString("SunshineExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sunshine configuration file not found. Please ensure Sunshine is installed. 的本地化字符串。
        /// </summary>
        internal static string SunshineNotFound {
            get {
                return ResourceManager.GetString("SunshineNotFound", resourceCulture);
            }
        }
    }
}
