//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PotatoVN.App.PluginBase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PotatoVN.App.PluginBase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize game library and status with PotatoVN Server via local network..
        /// </summary>
        internal static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 局域网存档同步.
        /// </summary>
        internal static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Ui_Add {
            get {
                return ResourceManager.GetString("Ui_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Sync.
        /// </summary>
        internal static string Ui_AutoSync {
            get {
                return ResourceManager.GetString("Ui_AutoSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically sync saves via LAN before game launch..
        /// </summary>
        internal static string Ui_AutoSyncDescription {
            get {
                return ResourceManager.GetString("Ui_AutoSyncDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path for {0} not found: {1}.
        /// </summary>
        internal static string Ui_Error_PathNotFound {
            get {
                return ResourceManager.GetString("Ui_Error_PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync path for {0} is not set..
        /// </summary>
        internal static string Ui_Error_SettingNotSet {
            get {
                return ResourceManager.GetString("Ui_Error_SettingNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Root.
        /// </summary>
        internal static string Ui_GameRoot {
            get {
                return ResourceManager.GetString("Ui_GameRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string Ui_Label {
            get {
                return ResourceManager.GetString("Ui_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanSync.
        /// </summary>
        internal static string Ui_LanSync {
            get {
                return ResourceManager.GetString("Ui_LanSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        internal static string Ui_NewFolder {
            get {
                return ResourceManager.GetString("Ui_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string Ui_Path {
            get {
                return ResourceManager.GetString("Ui_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter directory path....
        /// </summary>
        internal static string Ui_PathPlaceholder {
            get {
                return ResourceManager.GetString("Ui_PathPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Ui_Remove {
            get {
                return ResourceManager.GetString("Ui_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Directories.
        /// </summary>
        internal static string Ui_SyncDirectories {
            get {
                return ResourceManager.GetString("Ui_SyncDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync error: {0}.
        /// </summary>
        internal static string Ui_SyncError {
            get {
                return ResourceManager.GetString("Ui_SyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote save is newer. Synced from remote successfully..
        /// </summary>
        internal static string Ui_SyncFromRemoteSuccess {
            get {
                return ResourceManager.GetString("Ui_SyncFromRemoteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local save is newer. Synced to remote successfully..
        /// </summary>
        internal static string Ui_SyncToRemoteSuccess {
            get {
                return ResourceManager.GetString("Ui_SyncToRemoteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save is up to date..
        /// </summary>
        internal static string Ui_SyncUpToDate {
            get {
                return ResourceManager.GetString("Ui_SyncUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Data.
        /// </summary>
        internal static string Ui_UserData {
            get {
                return ResourceManager.GetString("Ui_UserData", resourceCulture);
            }
        }
    }
}
